when = "2008-09-21T09:15:19-06:00"
processed = "2020-04-14T15:38:15.263923700-06:00"
tags = ["Axe", "BMW R1200GS Adventure", "Beer", "Camping", "Cooking", "Fire", "Honda CRF 230L", "Horse", "Motorcycle", "Power Line", "Rain", "Tent", "Tool", "Yamaha XT 250"]
