# https://rust-lang.github.io/rustfmt/
unstable_features = true
edition = "2018"
enum_discrim_align_threshold = 10
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
max_width = 80
merge_imports = true
newline_style = "Unix"
struct_field_align_threshold = 0
use_try_shorthand = true
wrap_comments = true