[package]
name = "static-from-exif"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
edition = "2018"

[dependencies]
hashbrown = "0.7"
toml = "0.5"
regex = "1"
serde_derive = "1"
yarte = "0.6"