[package]
name = "static-from-exif"
version = "0.1.0"
authors = ["Jason Abbott <you@example.com>"]
edition = "2018"

[dependencies]
kamadak-exif = "0.5"
hashbrown = "0.7"
lazy_static = "1"
chrono = { version = "0.4", features = ["serde"] }
toml = "0.5"
regex = "1"
rexiv2 = "0.9"
#photon-rs = "0.1.0"
#libvips = "1.1.5"
#imageflow_core = { git = "https://github.com/imazen/imageflow" }
serde = { version = "1.0", features = ["derive"] }
yarte = "0.7"