[package]
name = "static-from-exif"
version = "0.1.0"
authors = ["Jason Abbott <you@example.com>"]
edition = "2018"

[dependencies]
hashbrown = "0.7"
lazy_static = "1"
toml = "0.5"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
yarte = "0.6"