
# https://yarte.netlify.com/config.html
# root dir of templates
[main]
dir = "templates"
debug = "code"

# Alias for partials. In call, change the start of partial path with one of this, if exist.
[partials]
head = "./partials/head"
categories = "./partials/categories"
footer = "./partials/footer"
navigation = "./partials/navigation"
head_facebook = "./partials/head_facebook"
side_menu = "./partials/side_menu"
contact_link = "./partials/contact_link"

[debug]
# prettyprint themes, put anything for options
theme = "zenburn"
grid = true
header = true
number_line = true
paging = false
short = false