
# https://yarte.netlify.com/config.html
# root dir of templates
[main]
dir = "templates"
#debug = "code"

[partials]
categories = "./partials/categories"
category_selectors = "./partials/category_selectors"
contact_link = "./partials/contact_link"
footer = "./partials/footer"
header = "./partials/header"
html_head = "./partials/html_head"
html_head_facebook = "./partials/head_facebook"
json_ld = "./partials/json_ld"
navigation = "./partials/navigation"
side_menu = "./partials/side_menu"

[debug]
theme = "zenburn"
grid = true
header = true
number_line = false
paging = false
short = true