
# https://yarte.netlify.com/config.html
# root dir of templates
[main]
dir = "templates"
#debug = "code"

[partials]
head = "./partials/head"
categories = "./partials/categories"
footer = "./partials/footer"
navigation = "./partials/navigation"
head_facebook = "./partials/head_facebook"
side_menu = "./partials/side_menu"
contact_link = "./partials/contact_link"

[debug]
theme = "zenburn"
grid = true
header = true
number_line = false
paging = false
short = true