title = "Boiling Over"
summary = """Finally. I’ve been telling Kayla’s Polish boyfriend Nick that we’d \
ride for more than a year now. This may be his last summer in America for a \
while so it had to happen. We did the quick, sort of standard loop along the \
backside of the Boise Ridge, Humpty and Daggett. It was a nice workout."""
cover_photo_index = 4

[categories]
who = "Friends"
when = 2017
where = ["Boise National Forest","Boise Ridge"]
what = "KTM 500 XC-W"