title = "Bruneau's Red Light District"
summary = """I signed up for a hiking group camp-out at Bruneau Dunes. I’ve \
visited several times but never camped there so that sounded interesting. And \
I’ve never visited the observatory, which is on the itinerary, which also \
seemed interesting. And I don’t know any of the people so figured that could \
be interesting as well. Here goes nothing."""
cover_photo_index = 3

[categories]
who = "Friends"
when = 2019
where = ["Owhyees","Bruneau"]
what = "KTM 1290 SAR"