title = "Atlanta Loop"
summary = """Michael and I make a loop between Idaho City, Rocky Bar and \
Atlanta, Idaho, down forest roads, through a bit of snow, and finally ridge-top \
single track. It was a good thing he brought a saw or we might have missed \
“whoopty hell.”"""
cover_photo_index = 9

[categories]
who = "Friends"
when = 2013
where = ["Boise National Forest"]
what = "KTM 500 XC-W"