title = "November Solo Sunset",
summary = """I find the sun still up and the weather nice after I finish \
weekend chores so head out for the usual jaunt up Rocky Canyon Road to the \
ridge and back down Trail 4. Or that’s the plan."""
when = "2019"
who = "Solo"
location = ["Boise Ridge"]
what = "KTM 1290 SAR"