when = "2008-09-19T18:38:53-06:00"
processed = "2020-04-14T15:38:13.840255100-06:00"
tags = ["BMW R1200GS Adventure", "Bar", "Beer", "Dancing", "Dirt Road", "Fire", "Gesturing", "Honda CRF 230L", "J&E Stop", "Lake", "Lichen", "Memorial", "Moon", "Motorcycle", "Mountain", "Night", "Outcrop", "Power Line", "Restaurant", "Sign", "Smoke", "Smoking", "Spider", "Stars", "Store", "Tent", "Yamaha XT 250"]
