# https://github.com/sunng87/handlebars-rust

series_index_pattern = "^(\\d+)\\."
# source to target slug
redirects = [
   ["brother-rider-2013-a-night-in-pierce", "brother-ride-2013"],
   ["backroads-to-college", "panhandle-past-and-future"],
   ["owyhee-snow-and-sands-uplands", "owyhee-snow-and-sand"],
   ["lunch-at-trinity-lookout", "trinity-lookout-lunch"]
]

[photo]
index_pattern = "_(\\d{3})-of-(\\d{3})\\.jpg$"

   [photo.size]
   large = 4096
   regular = 2048
   small = 1024
   thumb = 256

   [photo.exif]
   # source to target text replacements
   camera = [
      ["NIKON", "Nikon"],
      ["ILCE-7R", "Sony α7ʀ"],
      ["ILCE-7RM2", "Sony α7ʀ II"],
      ["Sony α7ʀM2", "Sony α7ʀ II"],
      ["VS980 4G", "LG G2"],
      ["XT1060", "Motorola Moto X"],
      ["TG-4", "Olympus Tough TG-3"]
   ]
   software = [
      ['Photoshop Lightroom', 'Lightroom']
   ]
   lens = [
      ['FE 35mm', 'Sony FE 35mm ƒ2.8'],
      ['FE 55mm', 'Sony FE 55mm ƒ1.8'],
      ['FE 90mm', 'Sony FE 90mm ƒ2.8 OSS'],
      ['58.0 mm f/1.4', 'Voigtländer Nokton 58mm ƒ1.4 SL II'],
      ['14.0 mm f/2.8', 'Samyang 14mm ƒ2.8'],
      ['50.0 mm f/1.4', 'Sigma 50mm ƒ1.4 EX DG'],
   #   [
   #      '35.0 mm f/2.0',
   #      /D700/.test(camera],
   #         ? 'Zeiss Distagon T* 2/35 ZF.2'
   #         : 'Nikkor 35mm ƒ2.0D'
   #   ],
      ['100.0 mm f/2.0', 'Zeiss Makro-Planar T* 2/100 ZF.2'],
      ['150.0 mm f/2.8', 'Sigma 150mm ƒ2.8 EX DG HSM APO'],
      ['90.0 mm f/2.8', 'Tamron 90mm ƒ2.8 SP AF Di'],
      ['24.0 mm f/3.5', 'Nikkor PC-E 24mm ƒ3.5D ED'],
      ['14.0-24.0 mm f/2.8', 'Nikon 14–24mm ƒ2.8G ED'],
      ['24.0-70.0 mm f/2.8', 'Nikon 24–70mm ƒ2.8G ED'],
      ['17.0-55.0 mm f/2.8', 'Nikon 17–55mm ƒ2.8G'],
      ['10.0-20.0 mm f/4.0-5.6', 'Sigma 10–20mm ƒ4–5.6 EX DC HSM'],
      ['1 NIKKOR VR 30-110mm f/3.8-5.6', 'Nikkor 1 30–110mm ƒ3.8–5.6 VR'],
      ['1 NIKKOR VR 10-30mm f/3.5-5.6', 'Nikkor 1 10–30mm ƒ3.5–5.6 VR'],
      ['18.0-200.0 mm f/3.5-5.6', 'Nikkor 18–200mm ƒ3.5–5.6G ED VR'],
      ['Voigtlander Heliar 15mm', 'Voigtländer Heliar 15mm ƒ4.5 III']
   ]

