repo_url = "https://github.com/trailimage/"
author_name = "Jason Abbott"

# source to target slug
redirects = [
   ["brother-rider-2013-a-night-in-pierce", "brother-ride-2013"],
   ["backroads-to-college", "panhandle-past-and-future"],
   ["owyhee-snow-and-sands-uplands", "owyhee-snow-and-sand"],
   ["lunch-at-trinity-lookout", "trinity-lookout-lunch"]
]
ignore_folders = [
    "about",
    "category-menu",
    "css",
    "fonts",
    "img",
    "mobile-menu",
    "js",
    "map",
    "photo-tag",
    "who",
    "what",
    "when",
    "where"
]

[featured_post]
path = "ruminations"

[site]
title = "Trail Image"
subtitle = "Adventure Photography by Jason Abbott"
description = "Stories, images and videos of small adventure trips in and around the state of Idaho"
url = "https://trailimage.com"
post_alias = "Adventure"

    [site.logo]
    url = "img/logo-large.png"
    width = 200
    height = 200

    [site.company_logo]
    url = "img/logo-title.png"
    width = 308
    height = 60

[owner]
name = "Jason Abbott"
urls = [
    "https://www.facebook.com/jason.e.abbott",
    "http://www.flickr.com/photos/boise",
    "https://www.youtube.com/user/trailimage",
    "https://twitter.com/trailimage"
]
    [owner.image]
    url = "img/face5_full.jpg"
    width = 300
    height = 300

[style]
# Maximum pixel height of static maps displayed with post summaries
inline_map_height = 200
# Pixel width of main content used to compute generated image widths
content_width = 650

[category]
# Match name of "what" category to transportation mode that may in turn
# match an icon
what_regex = [
    ["motorcycle", "(KTM|BMW|Honda)"],
    ["bicycle", "bicycle"],
    ["hike", "hike"],
    ["jeep", "jeep"]
]

# Which category kinds to display and in what order
display = ["when", "who", "what", "where"]

    [category.icon]
    # Map category kind to material icon
    # https://material.io/icons/
    who = "person"
    what = "directions"
    when = "date_range"
    where = "map"
    default = "local_offer"

[photo]
capture_index = "^(?P<index>\\d{3}).(?P<ext>jpg|png|tif)$"
# type of image files from which photo sizes are rendered
source_ext = ".tif"
source_size = 2048
output_ext = ".webp"

remove_tags = [
    'Idaho',
    'United States of America',
    'Abbott',
    'LensTagger',
    'Boise'
]

   [photo.size]
   large = 2048
   medium = 1024
   small = 320
   thumb = 256

   [photo.exif]
   # source to target text replacements
   camera = [
      ["NIKON", "Nikon"],
      ["ILCE-7R", "Sony α7ʀ"],
      ["ILCE-7RM2", "Sony α7ʀ II"],
      ["Sony α7ʀM2", "Sony α7ʀ II"],
      ["VS980 4G", "LG G2"],
      ["XT1060", "Motorola Moto X"],
      ["TG-4", "Olympus Tough TG-3"]
   ]
   software = [
      ['Photoshop Lightroom', 'Lightroom']
   ]
   lens = [
      ['FE 35mm', 'Sony FE 35mm ƒ2.8'],
      ['FE 55mm', 'Sony FE 55mm ƒ1.8'],
      ['FE 90mm', 'Sony FE 90mm ƒ2.8 OSS'],
      ['58.0 mm f/1.4', 'Voigtländer Nokton 58mm ƒ1.4 SL II'],
      ['14.0 mm f/2.8', 'Samyang 14mm ƒ2.8'],
      ['50.0 mm f/1.4', 'Sigma 50mm ƒ1.4 EX DG'],
   #   [
   #      '35.0 mm f/2.0',
   #      /D700/.test(camera],
   #         ? 'Zeiss Distagon T* 2/35 ZF.2'
   #         : 'Nikkor 35mm ƒ2.0D'
   #   ],
      ['100.0 mm f/2.0', 'Zeiss Makro-Planar T* 2/100 ZF.2'],
      ['150.0 mm f/2.8', 'Sigma 150mm ƒ2.8 EX DG HSM APO'],
      ['90.0 mm f/2.8', 'Tamron 90mm ƒ2.8 SP AF Di'],
      ['24.0 mm f/3.5', 'Nikkor PC-E 24mm ƒ3.5D ED'],
      ['14.0-24.0 mm f/2.8', 'Nikon 14–24mm ƒ2.8G ED'],
      ['24.0-70.0 mm f/2.8', 'Nikon 24–70mm ƒ2.8G ED'],
      ['17.0-55.0 mm f/2.8', 'Nikon 17–55mm ƒ2.8G'],
      ['10.0-20.0 mm f/4.0-5.6', 'Sigma 10–20mm ƒ4–5.6 EX DC HSM'],
      ['1 NIKKOR VR 30-110mm f/3.8-5.6', 'Nikkor 1 30–110mm ƒ3.8–5.6 VR'],
      ['1 NIKKOR VR 10-30mm f/3.5-5.6', 'Nikkor 1 10–30mm ƒ3.5–5.6 VR'],
      ['18.0-200.0 mm f/3.5-5.6', 'Nikkor 18–200mm ƒ3.5–5.6G ED VR'],
      ['Voigtlander Heliar 15mm', 'Voigtländer Heliar 15mm ƒ4.5 III']
   ]

[facebook]
app_id = "599065673763481"
page_id = "241863632579825"
site_id = "578261855525416"
admin_id = "1332883594"
author_url = "https://www.facebook.com/jason.e.abbott"

[mapbox]
max_static_markers = 70
pin_image = "https://www.trailimage.com/p.png"

    [mapbox.style]
    # used for interactive maps
    dynamic = "jabbott7/cj1qniq9r00322sqxt3pastcf"
    # used for static maps
    static = "jabbott7/cj1prg25g002o2ro2xtzos6cy"

[google]
project_id = "316480757902"
analytics_id = "22180727"
blog_id = "118459106898417641"

[gps_track]
min_track_points = 5
max_point_deviation_feet = 0.5
max_possible_speed_mph = 150
allow_download = true


#    link: {
#       googleEarth:
#          'https://earth.google.com/web/@{lat},{lon},1100a,{altitude}d,35y,0h,0t,0r',
#       gaiaGPS:
#          'https://www.gaiagps.com/map/?layer=GaiaTopoRasterFeet&lat={lat}&lon={lon}&zoom={zoom}'
#    },