when = "2008-09-20T07:25:49-06:00"
processed = "2020-04-14T15:38:14.678734600-06:00"
tags = ["Ailing", "BMW R1200GS Adventure", "Beer", "Camp Chair", "Chair", "Coffee", "Dirt Road", "Drinking", "Fire", "Honda CRF 230L", "Motorcycle", "Mountain", "Night", "Outcrop", "Photographing", "Rain", "River", "Sign", "Sunrise", "Tent", "Throwing", "Throwing Rocks", "Yamaha XT 250"]
